/**
 * Pre-shape the site's fixed words into glyph outlines (DESIGN.md §V3).
 *
 *   node scripts/shape-words.mjs
 *
 * Writes lib/glass/word-paths.ts. Re-run after changing the fonts or the word
 * list. Visitor-typed briefs are shaped in the browser instead, by lazily
 * importing fontkit; both paths share lib/glass/shape.ts.
 */
import { createRequire } from "node:module"
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import path from "node:path"

const require = createRequire(import.meta.url)
const fontkit = require("fontkit")
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")

// Node 24 strips types from .ts on import, so the shared module is reused
// verbatim rather than duplicated here.
const { shapeText, serialise, detectScript } = await import(
  path.join(root, "lib/glass/shape.ts")
)

const FONTS = {
  arabic: {
    file: "public/fonts/reem-kufi-var.ttf",
    variation: { wght: 700 },
  },
  latin: {
    file: "public/fonts/anybody-var.ttf",
    variation: { wght: 900, wdth: 150 },
  },
}

const WORDS = [
  "نبني",
  "WE BUILD",
  "WEB",
  "MOBILE",
  "DESKTOP",
  "API",
  "AI",
  "NABNI",
]

const fonts = Object.fromEntries(
  Object.entries(FONTS).map(([script, cfg]) => [
    script,
    fontkit
      .create(readFileSync(path.join(root, cfg.file)))
      .getVariation(cfg.variation),
  ])
)

const out = {}
for (const word of WORDS) {
  const script = detectScript(word)
  // Two lines max, wrapped narrow: the hero box is portrait, so "WE BUILD"
  // reads better stacked than as one long ribbon. Single long words shrink.
  const shaped = shapeText(fonts[script], word, {
    size: 1,
    maxLines: 2,
    maxWidth: 4.2,
  })
  out[word] = serialise(word, shaped)
  const chars = shaped.glyphs.length
  console.log(
    `${word.padEnd(10)} ${script.padEnd(7)} ${chars} glyphs  ${shaped.width.toFixed(2)} × ${shaped.height.toFixed(2)}`
  )
}

const body = `/**
 * GENERATED by scripts/shape-words.mjs — do not edit.
 *
 * Glyph outlines for the site's fixed words, shaped with fontkit from the
 * OFL fonts in public/fonts (see public/fonts/LICENSE.md). Committed so the
 * first frame and the server-rendered placeholder never wait on a shaper.
 */
import type { SerialisedWord } from "./shape"

export const WORD_PATHS: Record<string, SerialisedWord> = ${JSON.stringify(out, null, 2)}

export const FIXED_WORDS = Object.keys(WORD_PATHS)
`

writeFileSync(path.join(root, "lib/glass/word-paths.ts"), body)
console.log(`\nwrote lib/glass/word-paths.ts (${(body.length / 1024).toFixed(1)} KB)`)
